server:
  port: 8080
spring:
  application:
    name: gateway8080
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
      - id: consumer-echo
        uri:
          http://localhost:8001
        predicates:
        - Path=/consumer/**
